/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odev;

import javax.swing.JOptionPane;

/**
 *
 * @author BATUHAN
 */
public class anaMenuPanel extends javax.swing.JFrame {

    /**
     * Creates new form anaMenuPanel
     */
    public anaMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sogutucuAc = new javax.swing.JButton();
        sogutucuKapat = new javax.swing.JButton();
        sicaklikGoruntule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(100, 80));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        sogutucuAc.setBackground(new java.awt.Color(255, 255, 255));
        sogutucuAc.setFont(new java.awt.Font("Stencil", 0, 28)); // NOI18N
        sogutucuAc.setText("SOGUTUCU AC");
        sogutucuAc.setMaximumSize(new java.awt.Dimension(149, 33));
        sogutucuAc.setMinimumSize(new java.awt.Dimension(149, 33));
        sogutucuAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sogutucuAcActionPerformed(evt);
            }
        });

        sogutucuKapat.setBackground(new java.awt.Color(255, 255, 255));
        sogutucuKapat.setFont(new java.awt.Font("Stencil", 0, 28)); // NOI18N
        sogutucuKapat.setText("SOGUTUCU KAPAT");
        sogutucuKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sogutucuKapatActionPerformed(evt);
            }
        });

        sicaklikGoruntule.setBackground(new java.awt.Color(255, 255, 255));
        sicaklikGoruntule.setFont(new java.awt.Font("Stencil", 0, 28)); // NOI18N
        sicaklikGoruntule.setText("SICAKLIGI GORUNTULE");
        sicaklikGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sicaklikGoruntuleActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CIHAZ ISLEMLERINIZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sogutucuKapat, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sicaklikGoruntule)
                            .addComponent(sogutucuAc, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(sicaklikGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(sogutucuAc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(sogutucuKapat)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    girisPanel giris = new girisPanel();
    private void sogutucuAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sogutucuAcActionPerformed
        if(giris.k1.getSogutucu().getDurum()==true)
            JOptionPane.showMessageDialog(null,"Soğutucu zaten açık.");
        else
        {
            giris.k1.getSogutucu().update();
        }
    }//GEN-LAST:event_sogutucuAcActionPerformed

    private void sogutucuKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sogutucuKapatActionPerformed
        if(giris.k1.getSogutucu().getDurum()==false)
            JOptionPane.showMessageDialog(null,"Soğutucu zaten kapalı.");
        else
        {
            giris.k1.getSogutucu().update();
        }
    }//GEN-LAST:event_sogutucuKapatActionPerformed

    private void sicaklikGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sicaklikGoruntuleActionPerformed
        JOptionPane.showMessageDialog(null,"Sıcaklık: "+giris.k1.getCihazSicaklik()+" °C");
    }//GEN-LAST:event_sicaklikGoruntuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaMenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaMenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaMenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaMenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaMenuPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sicaklikGoruntule;
    private javax.swing.JButton sogutucuAc;
    private javax.swing.JButton sogutucuKapat;
    // End of variables declaration//GEN-END:variables
}
